### ISSUE TITLE
Infobar and Mobdrops need to be updated.

### ISSUE THREAD

**Issue by Chaotic** [DiscipleOfEris/Windower4Addons#7]
https://discord.com/channels/185583111638089728/1088457067418898443

A few mobs in Fei'Yin are coming up wrong in both addons.  Most likely the database needs to be rebuilt after the update.

**Comment by DiscipleOfEris** [comment]
You are correct.

**Comment by DiscipleOfEris** [comment]
I have now updated both of these.
